Uploader strategies
RedHatInsights/insights-analytics-collector pull request #24
Opened 2024-05-20 15:57 UTC by dmzoneill

2024-07-09 08:15 UTC, slemrmartin requested changes
It looks like your formatter is set wrong, the reformatted changes don't make sense.
Moreover I'm quite missing what are the real changes in the flood of reformating

2024-07-09 08:15 UTC, slemrmartin commented on insights_analytics_collector/collection.py
> +            self.logger.exception(
what's the reason for replacing simple string with multi-line strings with `#nopep8` exceptions?

2024-07-09 08:15 UTC, slemrmartin commented on insights_analytics_collector/collection.py
> +        self.last_gathered_entry = self.collector.last_gathered_entry_for(
what's the reason for this reformatting?

2026-02-09 19:34 UTC, dmzoneill commented
Closing due to formatting issues. Will recreate with proper formatting if these changes are still needed.

2026-02-09 19:34 UTC, closed without merging